// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace CommonAnnotatedSecurityKeys;

/// <summary>
/// The CASK-specific, general key kind. This kind value is distinct
/// from the separate, provider-specific, provider-defined key kind.
/// </summary>
public enum CaskKeyKind
{
    None = 0,

    /// <summary>
    /// Specifies a primary API or other security key.
    /// </summary>
    PrimaryKey = ('P' - 'A'), // Base64: index 0 == 'A'
                              // Bytewise: << 4 == 0, 0x00, 0b0000_0000

    /// <summary>
    /// Specifies a secret that is itself derived from a primary key.
    /// </summary>
    DerivedKey = ('D' - 'A'), // Base64 index 4 == 'D'
                              // Bytewise: << 4 == 28, 0x1c, 0b0100_0000
    /// <summary>
    /// Specifies a CASK hashed signature that incorporates a Message
    /// Authentication code of a derivation input generated by SHA-256.
    /// </summary>
    HMAC = ('H' - 'A'), // Base64 index 7 == 'H'
                        // Bytewise: << 4 == 28, 0x1c, 0b0111_0000
}
