// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace CommonAnnotatedSecurityKeys;

public enum KeyKind
{
    /// <summary>
    /// Specifies a 256-bit primary API or other security key.
    /// </summary>
    Key256Bit = ('A' - 'A'), // Base64: index 0 == 'A'
                             // Bytewise: << 2 == 0, 0x00, 0b0000_0000

    /// <summary>
    /// Specifies a CASK hashed signature that incorporates a Message
    /// Authentication code of a derivation input generated by SHA-256.
    /// </summary>
    Hash256Bit = ('H' - 'A'), // Base64 index 7 == 'H'
                              // Bytewise: << 2 == 28, 0x1c, 0b0001_1100

    /// <summary>
    /// Specifies a CASK hashed signature that incorporates a Message
    /// Authentication code of a derivation input generated by SHA-384.
    /// </summary>
    Hash384Bit = ('I' - 'A'), // Base64 index 8 == 'H'
                              // Bytewise: << 2 == 32, 0x20, 0b0010_0000
}
